"""empty message

Revision ID: 2ea50ba912e5
Revises: 
Create Date: 2018-04-19 13:06:28.441794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea50ba912e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('ground', sa.String(length=100), nullable=True),
    sa.Column('customer', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('sign_date', sa.DateTime(), nullable=True),
    sa.Column('supply', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('supply')
    )
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_customer'), ['customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_ground'), ['ground'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_notes'), ['notes'], unique=False)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=240), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_region_name'), ['name'], unique=True)

    op.create_table('tender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=30), nullable=True),
    sa.Column('customer', sa.String(length=100), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('ground', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_customer'), ['customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_ground'), ['ground'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_notes'), ['notes'], unique=False)

    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_name', sa.String(length=180), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('inn', sa.String(length=15), nullable=False),
    sa.Column('region_name', sa.String(length=180), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_name'], ['region.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_clinic_name'), ['clinic_name'], unique=True)

    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('comments', sa.String(length=250), nullable=True),
    sa.Column('picture_filename', sa.String(length=250), nullable=True),
    sa.Column('picture_url', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.Column('next_visit', sa.DateTime(), nullable=True),
    sa.Column('date_of_request', sa.DateTime(), nullable=True),
    sa.Column('date_of_request2', sa.DateTime(), nullable=True),
    sa.Column('region_name', sa.String(length=180), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_name'], ['region.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_comments'), ['comments'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_person_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_phone'), ['phone'], unique=True)

    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('date_of_next_visit', sa.DateTime(), nullable=False),
    sa.Column('arrangements', sa.String(length=250), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_arrangements'), ['arrangements'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_arrangements'))

    op.drop_table('visit')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_phone'))
        batch_op.drop_index(batch_op.f('ix_person_name'))
        batch_op.drop_index(batch_op.f('ix_person_email'))
        batch_op.drop_index(batch_op.f('ix_person_department'))
        batch_op.drop_index(batch_op.f('ix_person_comments'))

    op.drop_table('person')
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_clinic_name'))
        batch_op.drop_index(batch_op.f('ix_clinic_address'))

    op.drop_table('clinic')
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_notes'))
        batch_op.drop_index(batch_op.f('ix_tender_ground'))
        batch_op.drop_index(batch_op.f('ix_tender_customer'))
        batch_op.drop_index(batch_op.f('ix_tender_company'))

    op.drop_table('tender')
    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_region_name'))

    op.drop_table('region')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    op.drop_table('followers')
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_notes'))
        batch_op.drop_index(batch_op.f('ix_contract_ground'))
        batch_op.drop_index(batch_op.f('ix_contract_customer'))
        batch_op.drop_index(batch_op.f('ix_contract_company'))

    op.drop_table('contract')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
