"""empty message

Revision ID: 5c8af7d09c18
Revises: 1089f6812a07
Create Date: 2018-05-17 14:32:52.009764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8af7d09c18'
down_revision = '1089f6812a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('ground', sa.String(length=100), nullable=True),
    sa.Column('customer', sa.String(length=100), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('sign_date', sa.DateTime(), nullable=True),
    sa.Column('supply', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.UniqueConstraint('supply')
    )
    with op.batch_alter_table('contract_archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_archive_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_archive_customer'), ['customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_archive_ground'), ['ground'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_archive_notes'), ['notes'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_archive_notes'))
        batch_op.drop_index(batch_op.f('ix_contract_archive_ground'))
        batch_op.drop_index(batch_op.f('ix_contract_archive_customer'))
        batch_op.drop_index(batch_op.f('ix_contract_archive_company'))

    op.drop_table('contract_archive')
    # ### end Alembic commands ###
