"""Person uploading pictures

Revision ID: 8ea040f8d29e
Revises: 1d74a39262e1
Create Date: 2018-04-04 17:07:37.001089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea040f8d29e'
down_revision = '1d74a39262e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_filename', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('picture_url', sa.String(), nullable=True))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('picture_url')
        batch_op.drop_column('picture_filename')

    # ### end Alembic commands ###
