"""add second date of request

Revision ID: 96ba09c69d39
Revises: d1cb8de1ec19
Create Date: 2018-04-17 09:19:58.257633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ba09c69d39'
down_revision = 'd1cb8de1ec19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_request2', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('date_of_request2')

    # ### end Alembic commands ###
