"""add Tender and Contract class

Revision ID: a3058fd9fb99
Revises: 96ba09c69d39
Create Date: 2018-04-17 10:38:15.318791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3058fd9fb99'
down_revision = '96ba09c69d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('game_date', sa.DateTime(), nullable=True),
    sa.Column('ground', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_ground'), ['ground'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_notes'), ['notes'], unique=False)

    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signDate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract')
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_notes'))
        batch_op.drop_index(batch_op.f('ix_tender_ground'))
        batch_op.drop_index(batch_op.f('ix_tender_company'))

    op.drop_table('tender')
    # ### end Alembic commands ###
