"""delete Contract class

Revision ID: fc03d2bd4d75
Revises: 2d48725d4f05
Create Date: 2018-04-17 11:52:22.378164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc03d2bd4d75'
down_revision = '2d48725d4f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_notes')

    op.drop_table('contract')
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_column('contract')

    op.create_table('contract',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('signDate', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('tender_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract', schema=None) as batch_op:
        batch_op.create_index('ix_contract_notes', ['notes'], unique=False)

    # ### end Alembic commands ###
